#!/usr/bin/env python 
# -*- coding: utf-8 -*-
# @Time    : 2019-07-22 16:02
# @Author  : 冯佳欣
# @File    : 389. Find the Difference.py
# @Desc    :
'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

'''


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        '''
        思路：这种就没有必要弄的多高深
        就是遍历t中的字符，看它在t中出现的次数和在s中出现的次数是否相同

        '''
        for letter in t:
            if s.count(letter) != t.count(letter):
                return letter
